# v2 syntax
version: "3.4"

# Named volumes
volumes:
  github-postgres-data:
    driver: local

services:
  # db
  db:
    image: postgres:13.0-alpine
    container_name: github-postgres-dev
    restart: unless-stopped
    ports:
      - "${DOCKER_DB_PORT:-9934}:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - github-postgres-data:/var/lib/postgresql/data
